package com.mytuin.gardenplanner.domain.repository

import com.mytuin.gardenplanner.domain.model.garden.Geometry
import com.mytuin.gardenplanner.domain.model.garden.GrowingSpace
import kotlinx.coroutines.flow.Flow

/**
 * Repository interface for GrowingSpace.
 *
 * DEC-041: updateGeometry writes the prior state to the history table
 * and updates the current row in a single transaction. Callers cannot
 * forget the atomicity because it is not their responsibility (A67=a).
 *
 * The history row id is generated by the implementation via injected
 * IdGenerator (A68=a).
 */
interface GrowingSpaceRepository {
    fun observeGrowingSpacesInGarden(gardenId: String): Flow<List<GrowingSpace>>

    fun observeGrowingSpace(id: String): Flow<GrowingSpace?>

    suspend fun getGrowingSpace(id: String): GrowingSpace?

    suspend fun insert(growingSpace: GrowingSpace)

    /**
     * Updates the geometry of an existing GrowingSpace. Preserves the
     * prior geometry in growing_space_history.
     *
     * Throws [IllegalStateException] if no GrowingSpace with [id] exists.
     */
    suspend fun updateGeometry(
        id: String,
        newGeometry: Geometry?,
        effectiveAt: Long,
        reason: String?,
    )
}
